name: Markdownlint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  markdownlint:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        architecture:
          - x64

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - run: npx markdownlint-cli *.md
